import Head from 'next/head'
import { BsMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle,AiFillYoutube,AiFillLinkedin} from 'react-icons/ai';
import { FaTiktok} from 'react-icons/fa'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Christopher Teko Belan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='bg-white px-10'>
        <section className='min-h-screen'>

          {/*Navbar part */}
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbyed</h1>
            <ul className='flex item-center'>
              <li>
                <BsMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-emerald-400 to-teal-400 text-white px-4 py-2 rounded-md ml-8'
                  href='#'>Resume</a>
              </li>
            </ul>
          </nav>
          {/* Presentation part */}
          <div className='text-center p-10 '>
            <h2 className='text-4xl py-2 text-emerald-600 font-medium'>
              Christopher Teko</h2>
            <h3 className='text-xl py-2'>Web develeper and Growth Hacker</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Freelancer providing services for web programming web marketing and growth aquisition.</p>
            <p>Join me down below to step up your business to the next level</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillYoutube />
            <AiFillLinkedin />
            <FaTiktok />
          </div>
        </section>
      </main>
    </div>
  );
}
